### ISSUE TITLE
Pipes not working (sometimes)

### ISSUE THREAD

**Issue by klueska** [brho/akaros#17]
I have a simple pipe test sitting on origin/failing-pipetest that periodically dies with a page fault.  It should always run to completion.

**Comment by klueska** [comment]
It turns out, it wasn't the pipes, but the fact that I was using fork() without an exec(), which is slightly broken on Akaros.  The gist of the problem is that child processes are not able to properly handle syscalls that do not complete immediately (i.e. when a kthread is put to sleep on a rendez and returns to userspace with SC_DONE == 0).  I noticed the problem because I was page faulting in the child as an early SCP, but the parent was clearly already a normal SCP (so the child should have been as well).  This info is stored in procdata, and is not currently being copied over to a forked process properly.
This is a result of not properly keeping  our fork() code up to date with additions to procinfo/procdata that affect forked processes.

I have a fix I am putting together that copies relevant portions of procinfo and procdata into a forked process, and then resets them properly if we happen to do an exec later.  I will push it out for review soon.

**Comment by akaros-notifier** [comment]
Resolved by:
https://groups.google.com/forum/#!topic/akaros/DFfhXDH8tCs
