### ISSUE TITLE
Errors while trying to build the kernel. 

### ISSUE THREAD

**Issue by mattgk1996** [brho/akaros#27]
I was trying to install akaros to try to implement another scheduling algorithm. But i cant seem install it. One error after the other. 
I built the cross compiler. x86_64
But i am not able to build the kernel. 

This is what i did.
opened gedit .bashrc
added this to the end of it-->export PATH="<pathofbin:$PATH"
saved it. opened a new terminal.
went to the akaros-master directory.
then-->sudo make
but the following error was reported
"
Could not find a x86_64-ucb-akaros- version of GCC/binutils. Be sure to build the cross-compiler and update your PATH
make: *** [cc-exists] Error 1
"

then tried-->
$sudo -s
$PATH="/home/matthew/install/x86_64-ucb-akaros-gcc/bin:$PATH"
$make

then i got this error.
"
  CC      kern/src/error.o
kern/src/error.c:3:1: error: expected expression at end of input
 const char *errno_strings[] = {
 ^
make[1]: *** [kern/src/error.o] Error 1
make: *** [kern/src] Error 2
"

Can someone please help me??

**Comment by akaros-notifier** [comment]
Hi -

On 2016-02-02 at 10:38 Matthew George Kallarackal
<notifications@github.com> wrote:
> I was trying to install akaros to try to implement another scheduling
> algorithm But i cant seem install it One error after the other I
> built the cross compiler x86_64 But i am not able to build the kernel 
> 
> This is what i did
> opened gedit bashrc
> added this to the end of it-->export PATH="<pathofbin:$PATH"
> saved it opened a new terminal
> went to the akaros-master directory
> then-->sudo make

I don't build it with sudo.  Maybe that is causing some issues?

> then i got this error
> "
>   CC      kern/src/erroro
> kern/src/errorc:3:1: error: expected expression at end of input
>  const char *errno_strings[] = {
>  ^
> make[1]: *** [kern/src/erroro] Error 1
> make: *** [kern/src] Error 2
> "

That looks a little weird.  For some debugging output, try this:

$ make V=1

That will give the commands make (via Kbuild) is using.  Then we can
try the command that is failing directly and try to debug that.

Also, the formatting of the error looks like it's losing characters.
For instance, the file is "kern/src/error.c", not "kern/src/errorc".

Barret

**Comment by akaros-notifier** [comment]
Keep in mind that kern/src/error.c is generated at compile time.  Take
a look at the top of kern/src/Kbuild. If the cross compiler isn't
working properly it wont be able to generate this file.

On Tue, Feb 2, 2016 at 11:26 AM, Barret Rhoden <brho@cs.berkeley.edu> wrote:
> Hi -
>
> On 2016-02-02 at 10:38 Matthew George Kallarackal
> <notifications@github.com> wrote:
>> I was trying to install akaros to try to implement another scheduling
>> algorithm But i cant seem install it One error after the other I
>> built the cross compiler x86_64 But i am not able to build the kernel
>>
>> This is what i did
>> opened gedit bashrc
>> added this to the end of it-->export PATH="<pathofbin:$PATH"
>> saved it opened a new terminal
>> went to the akaros-master directory
>> then-->sudo make
>
> I don't build it with sudo.  Maybe that is causing some issues?
>
>> then i got this error
>> "
>>   CC      kern/src/erroro
>> kern/src/errorc:3:1: error: expected expression at end of input
>>  const char *errno_strings[] = {
>>  ^
>> make[1]: *** [kern/src/erroro] Error 1
>> make: *** [kern/src] Error 2
>> "
>
> That looks a little weird.  For some debugging output, try this:
>
> $ make V=1
>
> That will give the commands make (via Kbuild) is using.  Then we can
> try the command that is failing directly and try to debug that.
>
> Also, the formatting of the error looks like it's losing characters.
> For instance, the file is "kern/src/error.c", not "kern/src/errorc".
>
> Barret
>
> --
> You received this message because you are subscribed to the Google Groups "Akaros" group.
> To unsubscribe from this group and stop receiving emails from it, send an email to akaros+unsubscribe@googlegroups.com.
> To post to this group, send email to akaros@googlegroups.com.
> For more options, visit https://groups.google.com/d/optout.



-- 
~Kevin

**Comment by akaros-notifier** [comment]
Or rather, if it can't read the .h file (possibly because permissions
are wrong because of the sudo) then the script wont generate this file
properly.

On Tue, Feb 2, 2016 at 11:28 AM, Kevin Klues <klueska@gmail.com> wrote:
> Keep in mind that kern/src/error.c is generated at compile time.  Take
> a look at the top of kern/src/Kbuild. If the cross compiler isn't
> working properly it wont be able to generate this file.
>
> On Tue, Feb 2, 2016 at 11:26 AM, Barret Rhoden <brho@cs.berkeley.edu> wrote:
>> Hi -
>>
>> On 2016-02-02 at 10:38 Matthew George Kallarackal
>> <notifications@github.com> wrote:
>>> I was trying to install akaros to try to implement another scheduling
>>> algorithm But i cant seem install it One error after the other I
>>> built the cross compiler x86_64 But i am not able to build the kernel
>>>
>>> This is what i did
>>> opened gedit bashrc
>>> added this to the end of it-->export PATH="<pathofbin:$PATH"
>>> saved it opened a new terminal
>>> went to the akaros-master directory
>>> then-->sudo make
>>
>> I don't build it with sudo.  Maybe that is causing some issues?
>>
>>> then i got this error
>>> "
>>>   CC      kern/src/erroro
>>> kern/src/errorc:3:1: error: expected expression at end of input
>>>  const char *errno_strings[] = {
>>>  ^
>>> make[1]: *** [kern/src/erroro] Error 1
>>> make: *** [kern/src] Error 2
>>> "
>>
>> That looks a little weird.  For some debugging output, try this:
>>
>> $ make V=1
>>
>> That will give the commands make (via Kbuild) is using.  Then we can
>> try the command that is failing directly and try to debug that.
>>
>> Also, the formatting of the error looks like it's losing characters.
>> For instance, the file is "kern/src/error.c", not "kern/src/errorc".
>>
>> Barret
>>
>> --
>> You received this message because you are subscribed to the Google Groups "Akaros" group.
>> To unsubscribe from this group and stop receiving emails from it, send an email to akaros+unsubscribe@googlegroups.com.
>> To post to this group, send email to akaros@googlegroups.com.
>> For more options, visit https://groups.google.com/d/optout.
>
>
>
> --
> ~Kevin



-- 
~Kevin

**Comment by mattgk1996** [comment]
Hey, 
I didnt initialise the PATH before i built the compiler. I think that was why I was getting all these errors.
Thanks a ton though!
