### ISSUE TITLE
ipv4 route delete bug

### ISSUE THREAD

**Issue by brho** [brho/akaros#32]
Dan triggered a bug in v4delroute() a while ago.  I forget the details, other than it was a bad kref release.  Dan might be able to recreate it.

**Comment by dancrossnyc** [comment]
I take it you're filing bugs?

I have a vague recollection of that; it may be that we fixed it at the time
or that it was symptomatic of some other corruption invalidating the kref
(which was also subsequently fixed).

**Comment by akaros-notifier** [comment]
On 2016-04-29 at 09:09 Dan Cross <notifications@github.com> wrote:
> I take it you're filing bugs?

I'm actually going through a pile of notes on my desk.  Some make it to
the level of bugs.  =)

> I have a vague recollection of that; it may be that we fixed it at
> the time or that it was symptomatic of some other corruption
> invalidating the kref (which was also subsequently fixed).

I don't recall any kernel patches at that time that could have fixed it,
and I think no one other than you has attempted to delete a route.  I'd
consider this closed if we can delete IP routes without crashing the
kernel.

Barret

p.s. aren't you supposed to be relaxing in Hawaii?  =)

**Comment by akaros-notifier** [comment]
On Fri, Apr 29, 2016 at 12:37 PM, Barret Rhoden <brho@cs.berkeley.edu>
wrote:

> On 2016-04-29 at 09:09 Dan Cross <notifications@github.com> wrote:
> > I take it you're filing bugs?
>
> I'm actually going through a pile of notes on my desk.  Some make it to
> the level of bugs.  =)


Cool. :-)

> I have a vague recollection of that; it may be that we fixed it at
> > the time or that it was symptomatic of some other corruption
> > invalidating the kref (which was also subsequently fixed).
>
> I don't recall any kernel patches at that time that could have fixed it,
> and I think no one other than you has attempted to delete a route.  I'd
> consider this closed if we can delete IP routes without crashing the
> kernel.
>

Okay; I'll test it out when I get back.

p.s. aren't you supposed to be relaxing in Hawaii?  =)
>

Yeah. I woke up at 3am and couldn't fall back asleep. :-(

**Comment by brho** [comment]
Probably fixed in 6871b7380c77 ("Fix route deletion.")
