### ISSUE TITLE
Have difficult in building Cross compiler

### ISSUE THREAD

**Issue by zhishuozheng** [brho/akaros#38]
I tried to build cross compiler but it returns some error
+cc[vmm]...
fatal error: libelf.h: no such file or directory
....
So that I install elfutils-libelf-devel. However, I have installed this package and the same mistake is still there. I have checked that the libelf.h have already existed in /usr/include. I don't know how to fix it and could anyone give me some idea?

Many thanks

**Comment by akaros-notifier** [comment]
Hi -

On 2017-04-25 at  2:57 zhishuozheng wrote:
> I tried to build cross compiler but it returns some error
> +cc[vmm]...
> fatal error: libelf.h: no such file or directory
> ....
> So that I install elfutils-libelf-devel. However, I have installed this package and the same mistake is still there. I don't know how to solve it and could anyone give me some idea to fix it?

It sounds like you are running "make tests", but first you need to run 

$ make apps-install

https://github.com/brho/akaros/blob/master/GETTING_STARTED.md#33-userspace

The complaint about libelf.h is for Akaros programs, so you need
elfutils for Akaros - not your native Linux.  "apps-install" will
install our port of elfutils alongside the Akaros toolchain.

Barret

**Comment by zhishuozheng** [comment]
No, actually, I just tried to make X86_64 and it returns error such as 

+cc[vmm]...
fatal error: libelf.h: no such file or directory
....

**Comment by akaros-notifier** [comment]
On 2017-04-25 at  6:20 zhishuozheng wrote:
> No, actually, I just tried to make X86_64 and it returns error such as 
> 
> +cc[vmm]...
> fatal error: libelf.h: no such file or directory
> ....
> 

Ah!  This is probably due to Ron's patch from last week (moved some elf
stuff to the VMM library), creating a circular dependency.  You'd only
notice the problem if you did a toolchain rebuild.

I'll try to come up with a fix and get back to you.

Barret

**Comment by akaros-notifier** [comment]
Hi -

On 2017-04-25 at 06:20 zhishuozheng <notifications@github.com> wrote:
> No, actually, I just tried to make X86_64 and it returns error such as 
> 
> +cc[vmm]...
> fatal error: libelf.h: no such file or directory
> ....
> 

I pushed a patch that fixes the problem for me.  Hopefully it works for
you too.  If not, let me know.  =)

Thanks for the report!

Barret

**Comment by zhishuozheng** [comment]
Thanks for you information. I am new to Linux and akaros. So I don't know what did "pushed a patch" mean. Could you tell me in detail?

Many thanks
emma

**Comment by zhishuozheng** [comment]
Thanks for your information. I pull it from github agian. And it fixes the problem.
