### ISSUE TITLE
fix our broken make system

### ISSUE THREAD

**Issue by rminnich** [brho/akaros#8]
You can't used the build system with emacs, period. This is really frustrating. The way errors messages come out does not allow you to use next-error. I have tried and failed to figure out why it does not work.

**Comment by klueska** [comment]
I never use emacs.  What can I do to test the error and come up with a fix?

**Comment by klueska** [comment]
Pull request to fix this issue:
https://github.com/brho/akaros/pull/11

On Fri, Sep 18, 2015 at 9:26 AM, ron minnich <notifications@github.com>
wrote:

> You can't used the build system with emacs, period. This is really
> frustrating. The way errors messages come out does not allow you to use
> next-error. I have tried and failed to figure out why it does not work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brho/akaros/issues/8>.
>



-- 
~Kevin
