### ISSUE TITLE
make install headers recursive

### ISSUE THREAD

**Issue by rminnich** [brho/akaros#9]
I have user/vmm/include which has files and directories init. The directories don't get copied and they should. Make the copy recursive or use rsync, take your pick.

**Comment by klueska** [comment]
Im trying to reproduce this, but the current virtio-r branch (where I assume your developing) doesn't seem to compile.  Do you have some local changes that need to be pushed?

ioapic.c: In function 'ioapic_read':
ioapic.c:122:7: error: 'a20addr' undeclared (first use in this function)
   if((a20addr & ~0x3) != ((a20addr+len-1) & ~0x3)) {
       ^
ioapic.c:122:7: note: each undeclared identifier is reported only once for each function it appears in
ioapic.c:122:36: error: 'len' undeclared (first use in this function)
   if((a20addr & ~0x3) != ((a20addr+len-1) & ~0x3)) {
                                    ^
ioapic.c:123:5: warning: implicit declaration of function 'BX_PANIC' [-Wimplicit-function-declaration]
     BX_PANIC(("I/O APIC read at address 0x" FMT_PHY_ADDRX " spans 32-bit boundary !", a20addr));
     ^
ioapic.c:123:45: error: expected ')' before 'FMT_PHY_ADDRX'
     BX_PANIC(("I/O APIC read at address 0x" FMT_PHY_ADDRX " spans 32-bit boundary !", a20addr));
                                             ^
ioapic.c:126:3: error: unknown type name 'Bit32u'
   Bit32u value = theIOAPIC->read_aligned(a20addr & ~0x3);
   ^
ioapic.c:126:18: error: 'theIOAPIC' undeclared (first use in this function)
   Bit32u value = theIOAPIC->read_aligned(a20addr & ~0x3);
                  ^
ioapic.c:128:8: error: 'Bit32u' undeclared (first use in this function)
     *((Bit32u *)data) = value;
        ^
ioapic.c:128:16: error: expected expression before ')' token
     *((Bit32u *)data) = value;
                ^
ioapic.c:134:8: error: 'Bit8u' undeclared (first use in this function)
     *((Bit8u *) data) = value & 0xff;
        ^
ioapic.c:134:15: error: expected expression before ')' token
     *((Bit8u *) data) = value & 0xff;
               ^
ioapic.c:136:8: error: 'Bit16u' undeclared (first use in this function)
     *((Bit16u *)data) = value & 0xffff;
        ^
ioapic.c:136:16: error: expected expression before ')' token
     *((Bit16u *)data) = value & 0xffff;
                ^
ioapic.c:138:57: error: expected ')' before 'FMT_PHY_ADDRX'
     BX_PANIC(("Unsupported I/O APIC read at address 0x" FMT_PHY_ADDRX ", len=%d", a20addr, len));
                                                         ^
ioapic.c: In function 'ioapic_write':
ioapic.c:175:5: error: case label not within a switch statement
     case 0x00: // set APIC ID
     ^
ioapic.c:177:9: error: unknown type name 'Bit8u'
         Bit8u newid = (value >> 24) & apic_id_mask;
         ^
ioapic.c:177:39: error: 'apic_id_mask' undeclared (first use in this function)
         Bit8u newid = (value >> 24) & apic_id_mask;
                                       ^
ioapic.c:178:9: warning: implicit declaration of function 'BX_INFO' [-Wimplicit-function-declaration]
         BX_INFO(("IOAPIC: setting id to 0x%x", newid));
         ^
ioapic.c:179:9: warning: implicit declaration of function 'set_id' [-Wimplicit-function-declaration]
         set_id (newid);
         ^
ioapic.c:182:5: error: case label not within a switch statement
     case 0x01: // version
     ^
ioapic.c:183:5: error: case label not within a switch statement
     case 0x02: // arbitration id
     ^
ioapic.c:184:60: error: 'ioregsel' undeclared (first use in this function)
       BX_INFO(("IOAPIC: could not write, IOREGSEL=0x%02x", ioregsel));
                                                            ^
ioapic.c:186:5: error: 'default' label not within a switch statement
     default:
     ^
ioapic.c:187:7: error: expected expression before 'int'
       int index = (ioregsel - 0x10) >> 1;
       ^
ioapic.c:188:33: error: 'BX_IOAPIC_NUM_PINS' undeclared (first use in this function)
       if (index >= 0 && index < BX_IOAPIC_NUM_PINS) {
                                 ^
ioapic.c:189:9: error: unknown type name 'bx_io_redirect_entry_t'
         bx_io_redirect_entry_t *entry = ioredtbl + index;
         ^
ioapic.c:189:41: error: 'ioredtbl' undeclared (first use in this function)
         bx_io_redirect_entry_t *entry = ioredtbl + index;
                                         ^
ioapic.c:191:16: error: request for member 'set_hi_part' in something not a structure or union
           entry->set_hi_part(value);
                ^
ioapic.c:193:16: error: request for member 'set_lo_part' in something not a structure or union
           entry->set_lo_part(value);
                ^
ioapic.c:195:14: error: request for member 'sprintf_self' in something not a structure or union
         entry->sprintf_self(buf);
              ^
ioapic.c:196:9: warning: implicit declaration of function 'BX_DEBUG' [-Wimplicit-function-declaration]
         BX_DEBUG(("IOAPIC: now entry[%d] is %s", index, buf));
         ^
ioapic.c:197:9: warning: implicit declaration of function 'service_ioapic' [-Wimplicit-function-declaration]
         service_ioapic();
         ^
ioapic.c:204:13: error: request for member 'id' in something not a structure or union
   ioapicregs.id
             ^
ioapic.c:205:2: error: expected ';' before 'default'
  default:
  ^
make[1]: *** [obj/ioapic.o] Error 1

**Comment by klueska** [comment]
I talked to Ron about this, and it was user-error, rather than a real problem (the error I reference above was unrelated and happened because he just hadn't pushed something back that was needed to build).

Ron was confused about the use of 'make xcc-install-headers' (which only installs kernel headers to the cross compiler), and 'make install-libs', which builds the user-space libraries that are bundled with akaros and installs them into the cross compiler along with their headers.  Ron was trying to use the former to do the latter...
